INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '06608386133', '1998-07-03', 'vitor@gmail.com', 'Vitor Lucas Fernandes Botelho');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '08027956412 ', '1989-04-24', 'david@gmail.com', 'David Oliveira de Carvalho');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '05842364417', '1990-08-10', 'karine@gmail.com', 'Karine Maria Gonçalves Cortez');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '03911279426 ', '1980-10-16', 'jairo@gmail.com', 'Jairo Jose da Silva Filho');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '07673414490 ', '1988-07-03', 'gustavo@gmail.com', 'Gustavo Pereira dos Santos');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '09099983450 ', '1990-12-16', 'leandro@gmail.com', 'Leandro José Paulo da Silva');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '09590535496 ', '1991-10-04', 'maria@gmail.com', 'Maria Nainam Silvino Araújo dos Santos');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '06075815490 ', '1989-01-11', 'jullieny@gmail.com', 'Jullieny Melo de Oliveira');
INSERT INTO TB_USUARIO (ID, CPF, DATA_NASCIMENTO, EMAIL, NOME) VALUES( NULL, '02436166439  ', '1977-06-25', 'rita@gmail.com', 'Rita de Cássia dos Santos');


INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Riacho Fundo 1', '71805406', 'casa 26', 'Brasilia', 'qn 05 conj 06', 26, 'DF', 1);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '48005015', 'anexo 3', 'Alagoinhas', 'Rua Lauro de Freitas', 3, 'BA', 2);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '45810970', 'casa 18', 'Porto Seguro', 'Rua Itagibá 85', 18, 'BA', 3);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '88501032', 'casa 18', 'Porto Seguro', 'Praça Siqueira Campos', 3, 'BA', 4);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '45810970', 'sobreloja 2', 'Lages', 'Rua Itagibá 85', 2, 'SC', 5);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '75503070', 'ed. Roberto Saltar', 'Itumbiara', 'Rua Franklin Xavier', 12, 'GO', 6);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Aruana', '49000230', 'Ed. Água Santa', 'Aracaju', 'Rua Acadêmica Núbia Marques', 301, 'SE', 7);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Oeste', '58700050', 'ed.Paque Cidade', 'Patos', 'Rua Doutor José Genuíno', 12, 'PB', 8);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Setor Central', '77803100', 'Casa 20', 'Araguaína', 'Avenida Paranaíba', 20, 'TO', 9);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '79002010', 'de 3276 a 5750 - lado par', 'Campo Grande', 'Avenida Noroeste', 12, 'MS', 1);
INSERT INTO TB_ENDERECO(ID, BAIRRO, CEP, COMPLEMENTO, LOCALIDADE, LOGRADOURO,	NUMERO, UF, USUARIO_ID) VALUES (NULL, 'Centro', '58010030', 'Casa 20', 'João Pessoa', 'Rua Tenente Retumba', 20, 'PB', 2);